<?php

function git_pull_menu() {
	$items['github/update'] = array(
		'page callback' => 'git_pull_receive_github_update',
		'type' => MENU_CALLBACK,
		'access callback' => TRUE
	);

	$items['admin/config/development/git_pull'] = array(
		'title' => 'Git Pull',
		'description' => 'Configuration for the Git Pull module.',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('git_pull_admin_form'),
		'access arguments' => array('administer site configuration'),
		'type' => MENU_NORMAL_ITEM,
	);

	return $items;
}

function git_pull_admin_form($form, &$form_state) {
	$form['git_pull_git_path'] = array(
		'#type' => 'textfield',
		'#title' => 'Git Path',
		'#default_value' => variable_get('git_pull_git_path'),
		'#size' => 40,
		'#maxlength' => 255,
		'#required' => TRUE,
		'#description' => 'The full path to your git executable.'
	);

	$form['git_pull_repo_path'] = array(
		'#type' => 'textfield',
		'#title' => 'Repository Path',
		'#default_value' => variable_get('git_pull_repo_path'),
		'#size' => 40,
		'#maxlength' => 255,
		'#required' => TRUE,
		'#description' => 'The full path to your git repository.'
	);

	return system_settings_form($form);
}

function git_pull_receive_github_update() {
	// retrieve paths
	$git_path = variable_get('git_pull_git_path');
	$repo_path = variable_get('git_pull_repo_path');
	// execute pull
	if (!empty($git_path) && !empty($repo_path)) {
		$output = shell_exec("cd $repo_path; $git_path pull;");
		preg_match('/^Already up-to-date|^Updating \w+\.\.\w+/m', $output, $matches);
		if (count($matches) > 0) {
			watchdog('git_pull', "Post processed, pulling for git: $matches[0]");
		}
		else {
			watchdog('git_pull', "Encountered an error when trying to git pull:\n$output");
		}
	}
	else {
		watchdog('git_pull', 'Post recieved, but module configuration not complete');
	}
	return;
}

